### DISCUSSION TITLE
Discussion about using circleci for tur-on-device

### DISCUSSION THREAD

**Discussion by T-Dynamos** [termux-user-repository/tur#748] [General]
Some details about circleci free plan:
* It gives 6000 build mintues (30,000 credits = 6000mins) each month.
* It does not have support for [32 bit arm cpu](https://circleci.com/docs/using-arm/#limitations).
* Each build has time restriction of [1 hour](https://support.circleci.com/hc/en-us/articles/4410707277083-Context-deadline-exceeded-after-1-hour-Build-timed-out-Free-tier-only).

> I tried [building blender](https://app.circleci.com/pipelines/github/T-Dynamos/tur-circleci-builder/6/workflows/7b267bf3-49c1-4c81-aa70-430cb98e30c9/jobs/4) using medium `resource_class`, but it timeouts:
> ```
> [5058/5513] Building CXX object source/blender/io/alembic/CMakeFiles/bf_io_alembic.dir/exporter/abc_writer_abstract.cc.o
> context deadline exceeded
> Try out a larger resource class or running tests in parallel to speed up job execution.  Upgrade your pricing plan to take advantage of longer max job runtimes.
> ```
> [Here](https://app.circleci.com/pipelines/github/T-Dynamos/tur-circleci-builder/7/workflows/f3c5bcdd-b65a-4a62-9967-879acd0392a7/jobs/5) is the successful build using large `resource_class` in 37mins.

More details: https://circleci.com/pricing/

<details>
  <summary>Minimal <tt>.circleci/config.yml</tt> (if somebody wants to build himself)</summary>

```yml
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.large
    steps:
      - run:
          name: "BUILD"
          environment:
            ARCH: aarch64
          command: |
            git clone https://github.com/T-Dynamos/tur --depth 1 --branch update-blender
            cd tur
            ./setup-environment.sh
            ./common-files/build-termux-docker.sh login ./scripts/setup-termux.sh
            docker system prune -a -f
            sudo chown -R 1000:1000 $(pwd)
            ./common-files/build-termux-docker.sh login ./build-package.sh -I tur-on-device/blender
      - store_artifacts:
          path: tur/output
workflows:
  build:
    jobs:
      - build
```
> For example here I am building blender

</details>

So my plan to impelement circleci into tur-on-device `aarch64` build is: 
Aarch64 build will trigger circleci pipeline and will print a url (in github actions) which will take user to the circleci page. User can view logs and download artifacts there.

Circleci workfile is hosted at : https://github.com/T-Dynamos/tur-circleci-builder

CC: @licy183 any suggestions?
